### ISSUE TITLE
First sensor group is reading the wrong values

### ISSUE THREAD

**Issue by DonHugo** [SequentMicrosystems/rtd-rpi#10]
i have connected all channels except RTD3 on one of my rtd-rpi boards
RTD5-RTD8 works fine
RTD1-RTD4 is not working properly. 
several readings from channel 4
```
pi@rpi-zw-01:~ $ rtd 1 read 4
35.084435
30.902273
30.902273
30.902273
29.323097
29.323097
34.212376
```

several readings from channel 5 but with the same RTD sensor used in previous test on channel 4 (the reading coresponds with expected result)
```
pi@rpi-zw-01:~ $ rtd 1 read 5
3.243091
3.243091
3.279506
3.279506
3.233865
3.285515
```

i get similar faulty readings from all the channels in group 1
this has worked before, problem has arriesed during autom winter 2022, no changes has been done to the system during this time
is there a way to see if it is a fault in the HW?

```
pi@rpi-zw-01:~ $ rtd -v
rtd v1.2.4 Copyright (c) 2016 - 2022 Sequent Microsystems

pi@rpi-zw-01:~ $ rtd 1 board
Mega RTD firmware version 1.13
Vin 5.013V, Vrasp 4.985V, CPU Temp 38C

pi@rpi-zw-01:~ $ rtd 1 styperd 1
1

pi@rpi-zw-01:~ $ rtd 1 styperd 2
1
```

pleas help!

**Comment by alexburcea2877** [comment]
Wat is the hardware version? You should see it printed on the card.

**Comment by DonHugo** [comment]
V5.0

tis 10 jan. 2023 kl. 00:15 skrev Alexandru Burcea ***@***.***

**Comment by alexburcea2877** [comment]
If you use pt100 sensors, check the j12 jumper it might not make good contact.
Can you put here pictures with both sides of the card?

**Comment by DonHugo** [comment]
i use pt 1000 sensors on this board.

![20230110_143111_E5189AA3](https://user-images.githubusercontent.com/2417618/211583260-746cd7ac-055f-46a3-9a59-e74673d41537.jpg)
![20230110_143151_C063C5F5](https://user-images.githubusercontent.com/2417618/211583273-c5a4b13d-ebe4-40c7-9c95-0628e4387f4e.jpg)

**Comment by alexburcea2877** [comment]
![RTDV5](https://user-images.githubusercontent.com/16224602/211587898-d39a9317-be25-4351-a349-37a8d5db278e.jpg)
Can you make a more detailed picture with the marked area (both sides)?
Or check if something like oxides are presented in that area and clean them if you can.

That jumper is used to set the PT100/PT1000 type of sensor and change the value of the ADC reference. My concern is that the PCB makes some oxides it will introduce a parasitic resistance that affect all the sensors in the group.

**Comment by DonHugo** [comment]
not sure if this is anny better, but the mark inbetween the two solder points in the picure above is damage in green color layer. i think this happend when i removed the solderd wire that connected this jumper when i got the board. 
![20230110_153129_15ABE22A_zoomed](https://user-images.githubusercontent.com/2417618/211597395-47f57440-21dc-405e-bb97-0634168258eb.jpg)

**Comment by alexburcea2877** [comment]
Check if something change when you clean the area

**Comment by DonHugo** [comment]
now i've removed some of the solder that was left and cleaned the area with
isopropyl alcohol. no difference!

**Comment by alexburcea2877** [comment]
Have no more idea except for ADC hardware failure. Let me know your order number so I can ask for a replacement or sales when you buy a new one. The problem is that the version we have now is working with PT100 only.

**Comment by DonHugo** [comment]
First off, thanks for the quick support!

it's too bad that you are not supporting PT1000 anymore, i have at least
one sensor that is a PT1000 i can easily replace with a PT100.
Do you think you will support PT1000 in future HW?





Order SH-3198

**Comment by alexburcea2877** [comment]
Switching from multiple channel ADC (witch we can not buy anymore) to single channel ADC it give us the advantage of no crosstalk between sensors but come with less flexibility for changing the PGA so we can support both types of sensors.
If you have many PT1000 sensors and no need for such precision, you can use a Building Automation Card to read the resistance of the sensors and compute the transformation in Raspberry Pi .

I see you already order a new card, I will try to get you a discount code for the next order, I do not know if I can do something for the current order but I will ask.
Thank you for supporting our products.

**Comment by DonHugo** [comment]
ok, I dont need several decimal  precision. What  level of precision can I
expect from the Building Automation card?

**Comment by alexburcea2877** [comment]
This is a hard question but generally speaking the worst precision is the pull-up resistor from the measuring circuit which is +/-1%. All other things are with one order of magnitude better than that, anyway if you need more precision you can calibrate the measurement circuit.
