### ISSUE TITLE
Release python module onto pypi?

### ISSUE THREAD

**Issue by Bingdom** [SequentMicrosystems/rtd-rpi#15]
Hi,

Is it possible that we could get the python modules deployed to PyPi?

This would then allow us to track updates with dependabot. For example,

We generally specify a ``requirements.txt`` with a collection of modules that our project uses. It could look something like this for us.
```py
rtd-rpi==1.3.0
```

Obviously it would also allow us to install the module as normal
```
python -m pip install rtd-rpi
```

This should also be available for the other python libraries like [this one](https://github.com/SequentMicrosystems/4relind-rpi/tree/main/python)

**Comment by alexburcea2877** [comment]
Hi 

We intend to publish our python libraries on the PyPi but never have the necessary time to do it .
There is no chance to do this in the next month or so, sorry.

Alex.

**Comment by Bingdom** [comment]
I am now receiving this deprecation notice after installing your modules with the latest version of pip:

DEPRECATION: Loading egg at /usr/local/lib/python3.12/site-packages/lib4relind-1.0.3-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330

pip 24.3 will be released in October 2024 (next month).

Related article:
https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html

Invoking setup.py directly to install a package will be deprecated, and using other tools to handle it would be preferred. In that case, I'd say it would be worth uploading and getting it working with PyPi, to avoid any problems in the future.

**Comment by Bingdom** [comment]
Oh checking now and I see you now have SMrtd. Awesome!

The only small issue is that it's missing a description. Other than that, I'll just close this issue now.

**Comment by alexburcea2877** [comment]
You figured out faster than I could answer.
