### ISSUE TITLE
problem after trying to update firmware

### ISSUE THREAD

**Issue by DonHugo** [SequentMicrosystems/rtd-rpi#2]
```
~/rtd-rpi/update $ ./update 0
You are ready to update the firmware on your board.
Your Raspberry Pi must be connected to the internet.
Type "yes" (without quotes) to continue or anything else to quit:
yes
CPUID: 4d0047000a51504734363520
Downloading firmware...               Done
Bootloader no answer!!!
~/rtd-rpi/update $ ./update 0
You are ready to update the firmware on your board.
Your Raspberry Pi must be connected to the internet.
Type "yes" (without quotes) to continue or anything else to quit:
yes
CPUID: 4d0047000a51504734363520
Downloading firmware...               Done
Programming the board...
Write fail!
FAIL to write!
```

After this it is no longer possible to to read from RTD sensors.
```
:~/rtd-rpi/update $ rtd 0 read 1
MEGA-RTD id 0 not detected
```

This was working before.

**Comment by alexburcea2877** [comment]
Hi, try to unplug   and plug back the board, you need to make sure it make good contact  in the 40 pins connector.
The board will work after a successful update, you need to try the update again.

**Comment by DonHugo** [comment]
This is what happens
i have tried a few time now, with differant result but same outcome.

`
~ $ cd rtd-rpi/update/
~/rtd-rpi/update $ ./update 0
You are ready to update the firmware on your board.
Your Raspberry Pi must be connected to the internet.
Type "yes" (without quotes) to continue or anything else to quit:
yes
CPUID: 4d0047000a51504734363520
Downloading firmware...               Done
Programming the board... 20%
Write fail!
FAIL to write!
~/rtd-rpi/update $ ./update 0
You are ready to update the firmware on your board.
Your Raspberry Pi must be connected to the internet.
Type "yes" (without quotes) to continue or anything else to quit:
yes
Bootloader no answer!!!
~/rtd-rpi/update $ ./update 0
You are ready to update the firmware on your board.
Your Raspberry Pi must be connected to the internet.
Type "yes" (without quotes) to continue or anything else to quit:
yes
read cmd NACK ret 0x00 !!!
Bootloader no answer!!!
~/rtd-rpi/update $ ./update 0
You are ready to update the firmware on your board.
Your Raspberry Pi must be connected to the internet.
Type "yes" (without quotes) to continue or anything else to quit:
yes
Bootloader no answer!!!

~/rtd-rpi/update $ sudo reboot

Linux raspberrypi 5.4.51-v7+ #1333 SMP Mon Aug 10 16:45:19 BST 2020 armv7l

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Thu Nov 12 19:11:43 2020
~ $ cd rtd-rpi/update/
/rtd-rpi/update $ ./update 0
You are ready to update the firmware on your board.
Your Raspberry Pi must be connected to the internet.
Type "yes" (without quotes) to continue or anything else to quit:
yes
CPUID: 4d0047000a51504734363520
Downloading firmware...               Done
Programming the board... 65%
Write fail!
FAIL to write!
`

**Comment by alexburcea2877** [comment]
It is strange, I do not see something like this but you should try until the update is complete.Or wait for me to change the update  program to do more retry.

**Comment by DonHugo** [comment]
ok, i will continue to try to upgrade. will you notify  when you have updated program to do more retrys?

**Comment by alexburcea2877** [comment]
Yes, thank you.

**Comment by DonHugo** [comment]
i appreciate the quick responce.
i have some other findings.
- performing update only finds the board right after(within minutes) the raspberry pi has been rebootet.
- i have been able to get the upgrade progess up to 99% but never completed.
- i have tried maybe 40+ time and ar unable to complete the upgrade.

right now im powering the setup from the raspberry pi, i have order a 5v 3A powerbrick to test with.

**Comment by DonHugo** [comment]
i finaly got at upgrade done, but i still cant read from sensors.

`~ $ rtd-rpi/update/update 0
You are ready to update the firmware on your board.
Your Raspberry Pi must be connected to the internet.
Type "yes" (without quotes) to continue or anything else to quit:
yes
CPUID: 4d0047000a51504734363520
Downloading firmware...               Done
Programming the board...100%         Done`

`~ $ rtd 0 read 1
MEGA-RTD id 0 not detected`

`~ $ rtd 0 board
MEGA-RTD id 0 not detected`

**Comment by alexburcea2877** [comment]
Is very hard to me to debug this issue without be able to reproduce. I implement some retry mechanism but before publish to github you can test it on your board/Raspberry combinations? Unzip the file and run-it on yours raspberry
[update.zip](https://github.com/SequentMicrosystems/rtd-rpi/files/5536484/update.zip)

**Comment by DonHugo** [comment]
this is the result from running update.zip.

`~/debug_rtd-rpi $ ./update 0
You are ready to update the firmware on your board.
Your Raspberry Pi must be connected to the internet.
Type "yes" (without quotes) to continue or anything else to quit:
yes
CPUID: 4d0047000a51504734363520
Downloading firmware...               Done
Programming the board... 40%
Write fail!
FAIL to write!`

`~/debug_rtd-rpi $ ./update 0
You are ready to update the firmware on your board.
Your Raspberry Pi must be connected to the internet.
Type "yes" (without quotes) to continue or anything else to quit:
yes
read cmd NACK ret 0x00 !!!
Bootloader no answer!!!`

`:~/debug_rtd-rpi $ ./update 0
You are ready to update the firmware on your board.
Your Raspberry Pi must be connected to the internet.
Type "yes" (without quotes) to continue or anything else to quit:
yes
Bootloader no answer!!!`

**Comment by alexburcea2877** [comment]
Can you tight the raspberry and rtd with the standoffs provided before try again?

**Comment by alexburcea2877** [comment]
Also you have to make sure the bit-rate of the i2c is 100Kbps  https://www.raspberrypi-spy.co.uk/2018/02/change-raspberry-pi-i2c-bus-speed/
You can try to lower this only for the update then put it back to 100000.
The ease way to figure out that the update has succeed is the status led (blink with 50% if update is in progress or main application is invalid  and   10% if the main application is running).

**Comment by DonHugo** [comment]
> Can you tight the raspberry and rtd with the standoffs provided before try again?

done, same problem.

> Also you have to make sure the bit-rate of the i2c is 100Kbps https://www.raspberrypi-spy.co.uk/2018/02/change-raspberry-pi-i2c-bus-speed/
> You can try to lower this only for the update then put it back to 100000.
> The ease way to figure out that the update has succeed is the status led (blink with 50% if update is in progress or main application is invalid and 10% if the main application is running).

i2c bitrate 50kbps same problem
i2cbitrate 100kbps same problem

all tests done with update.zip version..

**Comment by alexburcea2877** [comment]
You think you can make one more try with the new update program?
[update.zip](https://github.com/SequentMicrosystems/rtd-rpi/files/5539394/update.zip)
Please give me back the console output of the update tool.
If the update is done but your board not flashing like running the app (10% ON), power off the board and repeat the update. I cancel one update in progress and was unable to make it work until I power off the board.
 Thank you for helping me solve this.

**Comment by DonHugo** [comment]
`~ $ /home/pi/debug2_rtd-rpi/update 0
You are ready to update the firmware on your board.
Your Raspberry Pi must be connected to the internet.
Type "yes" (without quotes) to continue or anything else to quit:
yes
CPUID: 4d0047000a51504734363520
Downloading firmware...               Done
Programming the board... 79%
 Retry 11 times. Write fail!
FAIL to write!
:~ $ /home/pi/debug2_rtd-rpi/update 0
You are ready to update the firmware on your board.
Your Raspberry Pi must be connected to the internet.
Type "yes" (without quotes) to continue or anything else to quit:
yes
read cmd NACK ret 0x00 !!!
Bootloader no answer!!!`

when i get `Bootloader no answer!!!` that is the only responce until i reboot the pi.

**Comment by alexburcea2877** [comment]
Can you tell me the type of raspberry you use?

**Comment by DonHugo** [comment]
Pi 2 Model B v1.1

**Comment by alexburcea2877** [comment]
One more try:
[update.zip](https://github.com/SequentMicrosystems/rtd-rpi/files/5539702/update.zip)
If This fails, try to power the raspberry from the board, if you have, change the raspberry and if is not working and I do not have a bright idea, we will send you a new card and find a way to recaver this card for future testing.

**Comment by DonHugo** [comment]
nothing seams to happen with tha latest update.zip
/home/pi/debug3_rtd-rpi/ is the latest update.zip version


`~ $ date; /home/pi/debug3_rtd-rpi/update 0
Sat 14 Nov 10:00:51 GMT 2020`
`~ $ date; /home/pi/debug3_rtd-rpi/update 0
Sat 14 Nov 10:00:52 GMT 2020`
`~ $ date; /home/pi/debug3_rtd-rpi/update 0
Sat 14 Nov 10:00:53 GMT 2020`
`~ $ date; /home/pi/debug3_rtd-rpi/update 0
Sat 14 Nov 10:00:54 GMT 2020`
`~ $ date; /home/pi/debug3_rtd-rpi/update 0
Sat 14 Nov 10:00:55 GMT 2020`
`~ $ date; /home/pi/debug2_rtd-rpi/update 0
Sat 14 Nov 10:00:59 GMT 2020
You are ready to update the firmware on your board.
Your Raspberry Pi must be connected to the internet.
Type "yes" (without quotes) to continue or anything else to quit:
yes
Bootloader no answer!!!`
`~ $ date; /home/pi/debug2_rtd-rpi/update 0
Sat 14 Nov 10:01:05 GMT 2020
You are ready to update the firmware on your board.
Your Raspberry Pi must be connected to the internet.
Type "yes" (without quotes) to continue or anything else to quit:
yes
Bootloader no answer!!!`

**Comment by alexburcea2877** [comment]
If the update not start you have to restart the raspberry (or better to power them off then back on).
Let me know if you test with external power supply, if the result will be the same, we will send you a new board.

**Comment by DonHugo** [comment]
i have tested with rebooting the raspberry  and power off and the on but with no luck.
i have also tested with a new external 5v 3A powersupply with no luck.

i really appreciate if you can send me an new board.

**Comment by alexburcea2877** [comment]
Give me something related to your order, order number or order date and time to find it on our database.
Ca we find a way to recover the bad board from you for future analysis ?

**Comment by DonHugo** [comment]
> Give me something related to your order, order number or order date and time to find it on our database.

I was backer 74 with Confirmation Number: 9a048f1b15b3481b8b2469780d91ed23 


> Ca we find a way to recover the bad board from you for future analysis ?

sure, how do you want to do it?

**Comment by alexburcea2877** [comment]
Can we use email to continue this conversation? Mine is olcitu@gmail.com
Give me a email so you not need to share your email here, thank you.

**Comment by alexburcea2877** [comment]
I see that you buy 4 pics (if I am not wrong), You try to update only one?

**Comment by DonHugo** [comment]
> I see that you buy 4 pics (if I am not wrong), You try to update only one?

no, i only bought one 8-channe boardl with 8 sensors.

**Comment by alexburcea2877** [comment]
I was wrong, sorry.

**Comment by alexburcea2877** [comment]
It seems the Raspberry was the problem.
