### ISSUE TITLE
problems with temperature display

### ISSUE THREAD

**Issue by huyetct** [SequentMicrosystems/rtd-rpi#3]
Hi Alexburcea2877 , could you here help me?
I would like to display a number with only two digits after the decimal point in NODE-RED. 
(NODE-RED  URL: 192.168.1.21:1880/UI/#/.....)
I wonder how to make it show a fixed numbers (say 2 numbers) after the decimal point. For example
if TEMPERATURE = 26.5787 ---> Temperature  = 26.57

**Comment by alexburcea2877** [comment]
Hi,
You can use the following code in a function:
Temperature = parseFloat(Temperature.toFixed(2));

**Comment by huyetct** [comment]
Hi Alexburcea2877

original code:

newMsg= {payload: msg.payload};
if(parseFloat(msg.msg.payload) > 120 || parseFloat(msg.msg.payload) <-60 )
{
newMsg.payload = "26.1542";
}
return newMsg;


I changed it to:
msg.payload = parseFloat(msg.payload.toFixed(2));
return newMsg;

does not seem to work.

**Comment by alexburcea2877** [comment]
No, because you change msg.payload and return newMsg
Change to:
newMsg.payload = parseFloat(msg.payload.toFixed(2));
return newMsg;

**Comment by huyetct** [comment]
Hi Alexburcea2877
i changed it to:

newMsg.payload = parseFloat(msg.payload.toFixed(2));
return newMsg;

I don't understand why it still doesn't work.
Is there a way to send pictures? I want to send pictures for you to see

**Comment by alexburcea2877** [comment]
Hi, export the nodes involved in the measurement (rtd , function, and one used to display) by selecting these nodes and go to the upper right corner at the menu button and click "Export"  then select "Selected nodes" then click "copy to clipboard".
Paste the code here and I will try to fix it and send back. I must mention that I am not a node-red expert.

**Comment by huyetct** [comment]
Hi Alexburcea2877
I used your sample code, and didn't change anything.

https://github.com/SequentMicrosystems/rtd-rpi/blob/master/node-red/RTD_example1.json

Thank you very much.

**Comment by alexburcea2877** [comment]
That example use exe node to read the temperature, I will change it to display only 2 decimal places.
The better method to use the rtd is to install the [node](https://github.com/SequentMicrosystems/rtd-rpi/tree/master/node-red-contrib-sm-rtd) and use-it .

**Comment by alexburcea2877** [comment]
The code was not functioning because the message must be string. Please replace the code in the function node with this:

newMsg ={payload: msg.payload};
if(parseFloat(msg.payload) > 120 || parseFloat(msg.payload) < -60)
{
    newMsg.payload = "25.67";
}
newMsg.payload = parseFloat(newMsg.payload).toFixed(2).toString();
return newMsg;

**Comment by huyetct** [comment]
Hi Alexburcea2877
it worked really well.
thank you very much.

In addition, you said "The better method to use the rtd is to install the node and use-it"
What does this mean? can you say more details

**Comment by alexburcea2877** [comment]
Hi,
More instructions for installing the node you will find [here](https://github.com/SequentMicrosystems/rtd-rpi/tree/master/node-red-contrib-sm-rtd)
After installation you will find in the palete the "RTD" node, place the node, connect an "inject node" at is input and a "debug node" on the output to test it.

**Comment by huyetct** [comment]
Hi Alexburcea2877
thank you very much.
I will learn the way you instructed.
