### ISSUE TITLE
Only resistor value is presented in node-red node

### ISSUE THREAD

**Issue by DonHugo** [SequentMicrosystems/rtd-rpi#5]
When using the node-red RTD node i only get the resistor value independent if i tic the "Output sensor resistance" box or not.
i have pulled the latest git version and re installed the rtd node but the issue persist.

**Comment by alexburcea2877** [comment]
Thank you, the bug has been solved.
Update the repository, reinstall the node, restart the NodeRed and refresh the browser.

**Comment by DonHugo** [comment]
now the node wont install.

pi@rpi-zw-01:~ $ npm install ~/rtd-rpi/node-red-contrib-sm-rtd
npm WARN saveError ENOENT: no such file or directory, open '/home/pi/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN pi No description
npm WARN pi No repository field.
npm WARN pi No README data
npm WARN pi No license field.

**Comment by alexburcea2877** [comment]
You have to change directory to ".node-red" first:
$ cd .node-red

then: 
$ npm install ~/rtd-rpi/node-red-contrib-sm-rtd/

**Comment by DonHugo** [comment]
it works, thank you! 👍

**Comment by alexburcea2877** [comment]
Thank you for finding the bug.
