### ISSUE TITLE
how can the resistance measure above 390 ohms

### ISSUE THREAD

**Issue by betyty** [SequentMicrosystems/rtd-rpi#6]
Hi Alexburcea,
The RTD board uses a PT100 sensor and the maximum resistance of the PT100 actually measures 390 ohms. so when measuring resistances above 390 ohms the results are all around 410 ohms. how can resistors be above 390 ohms.
Thanks very much.

newMsg = { payload : msg.payload };
if(parseFloat (msg.payload) > 500 || parseFloat (msg.payload) < -60)
{
 newMsg.payload = " 0 ";
}
return newMsg ;

**Comment by alexburcea2877** [comment]
Hi,
I am not sure I understand, you connect to the RTD card a sensor with 390 ohms and the card measure 410 ohms?

**Comment by betyty** [comment]
for example I measured the resistance of the Heater about 1057.10ohms ~ 1368.02ohms. how can its resistance be measured?

**Comment by alexburcea2877** [comment]
With the current hardware version you can not measure resistances greater than 390 ohms.
We work on the new hardware version capable to measure both PT100 and PT1000, so you can measure resistances in the range of the PT1000 sensor. 
One quick solution for measuring out of range resistors is to place one known resistor in parallels for lower the total resistance, measure and do the math for finding unknown resistance.

**Comment by betyty** [comment]
Hi Alexburcea,
by calculation, how can display resistor value greater than 390 ohms?
thanks

newMsg = { payload : msg.payload };
if(parseFloat (msg.payload) > 500 || parseFloat (msg.payload) < -60)
{
newMsg.payload = " 0 ";
}
return newMsg ;

**Comment by alexburcea2877** [comment]
Hi betyty,
English is not my native language, try to use more words, I honestly do not understand what you ask.
If you ask how to calculate equivalent parallel resistance here a clue : https://en.wikipedia.org/wiki/Series_and_parallel_circuits

**Comment by betyty** [comment]
I understood.
Thanks for your answer
Thank you very much.
