### ISSUE TITLE
read value on sensor is way to high with PT1000 sensor

### ISSUE THREAD

**Issue by DonHugo** [SequentMicrosystems/rtd-rpi#8]
the resistor value is correct and the read value shoukd be around 20C.
```
~ $ rtd 1 read 5
223.538010
~ $ rtd 1 readres 5
1085.951782
~ $ rtd 1 styperd 2
1
```
```
:~ $ rtd 1 board
Mega RTD firmware version 1.10
Vin 5.146V, Vrasp 5.158V, CPU Temp 33C
:~ $ rtd 0 board
Mega RTD firmware version 1.10
Vin 5.144V, Vrasp 5.133V, CPU Temp 31C
:~ $ rtd -v
rtd v1.2.2 Copyright (c) 2016 - 2021 Sequent Microsystems

This is free software with ABSOLUTELY NO WARRANTY.
For details type: rtd -warranty
```
hardware version 5.0

**Comment by alexburcea2877** [comment]
Hi

You use a PT1000 sensor?
You can use PT1000 only with card hw version = 5.0 and you need to do some more things to work (like cut the jumper and inform the card that you use pt1000).

**Comment by alexburcea2877** [comment]
You cut the jumper of the corresponded 5-8 channels?

**Comment by DonHugo** [comment]
> Hi
> 
> You use a PT1000 sensor? 
> You can use PT1000 only with card hw version = 5.0 and you need to do some more things to work (like cut the jumper and inform the card that you use pt1000).

Yes i use a PT1000 sensor!
i only use it with card hw version = 5.0 and i have cut the jumper and informed the card that i use PT1000

**Comment by DonHugo** [comment]
> You cut the jumper of the corresponded 5-8 channels?

yes, i checked with a continuity tester on my multimeter as well.

**Comment by DonHugo** [comment]
i cut it on both sides

**Comment by alexburcea2877** [comment]
I will check on RTD card an get back to you.

**Comment by alexburcea2877** [comment]
Hi,
Thanks for the bug report, I release firmware version 1.11 that solves the problem, please do a firmware update.

Alex.

**Comment by DonHugo** [comment]
great now it works.

a off topic question, how does the calibartion work?

and a comment on dokumentation:

on https://sequentmicrosystems.com/collections/all-io-cards/products/rtd-data-acquisition-card-for-rpi you wright "The board is shipped with the jumpers removed (PT1000)" this is not true for my board at least.

**Comment by alexburcea2877** [comment]
Hi,

The calibration can be made in 2 points,  with well known  resistors type "rtd -h cal" for more info.
We decide to solder a wire instead of jumpers (sometimes have a non zero resistance).

Alex

**Comment by DonHugo** [comment]
ok, it still not very clear regarding calibration:
`Example:    rtd 0 cal 2 100.34; Send one point of calibration at 100.34 ohms for channel #2 on card #0`
in the example, what am i calibrating to? there is no mention of a expected temperatur with the ohms i am setting.
what will the result be?


"We decide to solder a wire instead of jumpers (sometimes have a non zero resistance)." then change the doumentation pleas.

**Comment by alexburcea2877** [comment]
Hi,

We add some more words in the documentation but the Idea is that we do not calibrate the sensor but the resistance readings of the card. Pick 2 well known resistor but not too close as values connect them on the same channel and tell the card what the  real  resistance value is connected (for first resistor then for the second resistor), now the card will compensate future resistance measurements. The relation between resistance and temperature is a fixed one as I explain in the documentation (maybe not too well), if you want to change this you have to do it in the Raspberry. 

I changed the documentation about select sensor type jumpers, thanks.

**Comment by DonHugo** [comment]
.
